name: Add Changelog Entry

on:
  workflow_dispatch:
    inputs:
      significance:
        description: "Significance of the change (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      type:
        description: "Type of change"
        required: true
        type: choice
        options:
          - added
          - changed
          - deprecated
          - removed
          - fixed
          - security
      entry:
        description: "Changelog entry text"
        required: true
        type: string
      filename:
        description: "Custom filename (optional, will use branch name if not provided)"
        required: false
        type: string

jobs:
  add-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add changelog entry
        uses: stellarwp/changelogger@main
        with:
          command: add
          significance: ${{ github.event.inputs.significance }}
          type: ${{ github.event.inputs.type }}
          entry: ${{ github.event.inputs.entry }}
          filename: ${{ github.event.inputs.filename }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add changelog entry"
          title: "chore: add changelog entry"
          body: |
            Adds a new changelog entry:

            - Significance: ${{ github.event.inputs.significance }}
            - Type: ${{ github.event.inputs.type }}
            - Entry: ${{ github.event.inputs.entry }}
            ${{ github.event.inputs.filename && format(' - Filename: {0}', github.event.inputs.filename) || '' }}
          branch: changelog/add-${{ github.sha }}
          base: ${{ github.ref_name }}
          delete-branch: true
