# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected and actual dist/ directories
        run: |
          # First check if there are any uncommitted changes
          if [ "$(git status --porcelain dist/ | wc -l)" -gt "0" ]; then
            echo "Error: There are uncommitted changes in the dist/ directory. Please commit your changes."
            git status dist/
            exit 1
          fi
          
          # Then check if the last commit modified dist/ files
          if [ "$(git log -1 --name-only --pretty=format: | grep '^dist/' | wc -l)" -eq "0" ]; then
            echo "Error: The latest commit does not include any changes to the dist/ directory."
            echo "Please rebuild and commit the dist/ directory before submitting this PR."
            exit 1
          fi
        id: diff

      # If dist/ was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
